[workspace]
members = [
    "flutter-download",
    "flutter-engine",
    "flutter-engine-sys",
    "flutter-glfw",
    "flutter-plugins",
    "flutter-winit",
]

exclude = [
    "flutter-app-demo"
]
