[package]
name = "flutter-glfw"
description = "Flutter engine embedder in rust"
version = "0.3.5"
authors = ["juju <gliheng@gmail.com>", "Sophie Tauchert <sophie@999eagle.moe>"]
keywords = ["flutter", "GUI"]
license = "MIT"
repository = "https://github.com/gliheng/flutter-rs"
edition = "2018"

[dependencies]
async-std = "1.4.0"
flutter-engine-sys = { path = "../flutter-engine-sys" }
flutter-engine = { path = "../flutter-engine", features = ["texture-registry"] }
flutter-plugins = { path = "../flutter-plugins" }
futures-task = "0.3.1"
glfw = "0.34.0"
gl = "0.14.0"
log = "0.4.8"
lazy_static = "1.4.0"
locale_config = "0.3.0"
parking_lot = "0.10.0"
