[package]
name = "flutter-engine-sys"
description = "flutter engine sys crate"
version = "0.3.5"
authors = ["juju <gliheng@gmail.com>"]
keywords = ["flutter", "GUI"]
license = "MIT"
edition = "2018"

[build-dependencies]
bindgen = "0.52.0"
dirs = "2.0.2"
